### ISSUE TITLE
tf_farming/farming_info presentation wrong

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_grid#1]
should probably link to other presentations (see main foundation wiki, can even include the content)

**Comment by despiegk** [comment]
https://threefoldfoundation.github.io/info_grid/#/tf_farming/farming_info

**Comment by yveskerwyn** [comment]
I've added separate section for the farming presentation, where this is also a link to all other ThreeFold presentations: https://threefoldfoundation.github.io/info_grid/#/tf_farming/tf_farming_presentation
