### ISSUE TITLE
Add Analytics Script

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/info_grid#10]
Add google analytics script to track web usage & where we need to improve for 1.1.0

- [ ] Setup Script 
- [ ] Add Script to website
- [ ] Test Traffic

**Comment by despiegk** [comment]
need to be for all wiki's

**Comment by VonSub** [comment]
- [ ] Grid
- [ ] Token
- [ ] Foundation

**Comment by VonSub** [comment]
tested
