### ISSUE TITLE
MBR error on Farmer machine 

### ISSUE THREAD

**Issue by siddiquagig** [threefoldfoundation/info_grid#109]
Farmer is getting following error when booting ZeroOS image.

Farmer name : Юрий
64-bit Machine

Other OS option also enabled in BIOS.

![mbr](https://user-images.githubusercontent.com/25789724/58462935-f2559e00-8143-11e9-8d44-a9a07706d553.jpg)

**Comment by Pishoy** [comment]
Please verify first boot order to be usb

**Comment by siddiquagig** [comment]
Issue solved by new image
