### ISSUE TITLE
Title is misformated (# does not make it a title)

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_grid#133]
https://threefoldfoundation.github.io/info_foundation/#/definitions/threefold_wallet

**Comment by Sacha96** [comment]
@sabrinasadik please check this, it's the foundation wiki. Problem on top of the page....

https://threefoldfoundation.github.io/info_foundation/#/definitions/threefold_wallet

**Comment by weynandkuijpers** [comment]
Done
