### ISSUE TITLE
fix broken 404 links on grid wiki developer sect

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#141]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/18591016/65757815-2eac0180-e118-11e9-93c9-dee21c2e92e9.png">
<img width="285" alt="image" src="https://user-images.githubusercontent.com/18591016/65757843-38ce0000-e118-11e9-8166-c76b56e11814.png">
all show a 404 not found except ethereum node example

**Comment by andhartl** [comment]
link to the wiki site: https://wiki.grid.tf/#/developers/readme

**Comment by VonSub** [comment]
fixed with @PeterNashaat

**Comment by VonSub** [comment]
see staging
