### ISSUE TITLE
Wiki display of capacity type is incorreect

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_grid#163]
The wiki page: https://wiki.grid.tf/#/tf_farming/capacity_types does not render correct.  The source file should is: 

https://github.com/threefoldfoundation/info_grid/blob/master/docs/tf_farming/capacity_types.md

and is a symbolic link do the real source file:

https://github.com/threefoldfoundation/info_grid/blob/master/docs/concepts/capacity_types.md

The rendering of the MD file is correct in GitHub, not sure why it does not render well in the wiki.

**Comment by PeterNashaat** [comment]
- wikis are working fine now and capacity_tybes are loaded correctly.

![image](https://user-images.githubusercontent.com/13523434/72179781-59337900-33ee-11ea-91ff-7ddbea5dfe82.png)
