### ISSUE TITLE
farmer section: Bring latest how to in production

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#21]
please bring https://github.com/threefoldfoundation/info_grid/blob/development/docs/tf_farming/farming_dev_setup.md

in wiki/production

**Comment by hossnys** [comment]
this [file](https://github.com/threefoldfoundation/info_grid/blob/master/docs/tf_farming/farming_setup.md) is in production wiki now instead as it point for latest zero-os image (1.5.0) which farmers will use .
