### ISSUE TITLE
Farmer section: bring latest how to on wiki

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#22]
please bring 

https://github.com/threefoldfoundation/info_grid/blob/development/docs/tf_farming/farming_dev_setup.md

in wiki/production

**Comment by weynandkuijpers** [comment]
Researched it - and have found solution - not sure whether it is the most smart one:
- stopped publication of the WIKI in the settings page
- restarted the WIKI publication in the settings page

All pages were regenerated and now represent the latest content.
