### ISSUE TITLE
IT Services in ThreeFold Grid wiki results in a 404

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/info_grid#37]
<https://threefoldfoundation.github.io/info_grid/#/concepts/it_services>

<img width="728" alt="screen shot 2018-11-26 at 18 28 23" src="https://user-images.githubusercontent.com/3900482/49030997-18a47c00-f1a9-11e8-93da-2e083f95b53e.png">

**Comment by andhartl** [comment]
solved
