### ISSUE TITLE
Different capacity formulas used in different places. 

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_grid#39]
We have to use one single capacity units calculation formula everywhere.

Latest version of the formula:
https://github.com/threefoldfoundation/info_grid/blob/development/docs/concepts/commercial_token_value_calculation.md

Old version of the formula:
https://github.com/threefoldfoundation/info_grid/blob/development/docs/concepts/token_generation_rules.md
https://github.com/threefoldfoundation/info_grid/blob/master/docs/calculators/4_Hardware%20Calcs%20Farming%20Pools%20_%20may%2010.xlsx

As far as I know, first one is the latest and correct.
Capacity calculator should be fixed and updated. 
Thank you.

**Comment by nbabenko** [comment]
@weynandkuijpers , can we close it now? is it fixed?

**Comment by andhartl** [comment]
done
