### ISSUE TITLE
not all capacity is coming up on the directory, PLS CHECK WHY URGENTLY

### ISSUE THREAD

**Issue by christopherhutton** [threefoldfoundation/info_grid#40]
GREEN EDGE CLOUD report that not all their capacity is showing on the directory, PLs check and report back

**Comment by christopherhutton** [comment]
boxes appear to def be on API so should appear in directory

**Comment by sabrinasadik** [comment]
@weynandkuijpers pls keep us updated

**Comment by weynandkuijpers** [comment]
Discussed this earlier this week with Guido Neuman - and explained hat all capacity is listed and online.

created spread sheet: https://docs.google.com/spreadsheets/d/1xGroPl3yljB5VYip91SW4F_zpoxwNLOsEsvreiw5vCk/edit#gid=1073179848

Somehow the information is misrepresented on the web page.

**Comment by andhartl** [comment]
@weynandkuijpers can you please open an issue on the directory repo? ty

**Comment by Pishoy** [comment]
is this issue still exist ?

**Comment by weynandkuijpers** [comment]
Issue  closed
