### ISSUE TITLE
 Info_grid generated md files has some broken links

### ISSUE THREAD

**Issue by ahmadnazih** [threefoldfoundation/info_grid#44]
- **/info_grid/docs/_sidebar.md** : problem with link:[Customers](/customers/README.md)

- **info_grid/docs/concepts/_sidebar.md** :  problem with link:[IT Services](concepts/it_services.md)

- **info_grid/docs/concepts/README.md** : problem with link:[IT services](concepts/it_services.md)

- **info_grid/docs/cooperatives/text.md** : problem with link:[Bancadati](/cooperatives/)

- **info_grid/docs/faq/certified.md** : problem with link:[Dave Gale](dave@edgaecloud.africa) & [Miroslaw Polski](miro@hpe.com) & [Dave Gale](dave@edgaecloud.africa)

- **info_grid/docs/faq/compete.md** : [unmanaged](/definitions/threefold_unmanaged_capacity.md)

- **info_grid/docs/faq/hosters/README.md** :  [How will the ThreeFold Grid be implemented in emerging markets?](/faq/emerging_markets.md)

- All Links in  **info_grid/docs/tf_farming/sidebar_backup.md** need to be revised and fixed

- All Links in **info_grid/docs/tf_farming/backup_sidebar.md** need to be revised and fixed

- **info_grid/docs/tf_farming/threefold_principles.md** :  problem with link **Token Generation Rules For Farming** 

- **info_grid/docs/online_meetings/agile_collaboration.md** : problem with zoom meeting link

- **info_grid/docs/technology/README.md** : problem with link:**atomic swaps** & **This**

**Comment by VonSub** [comment]
info_grid/docs/online_meetings/agile_collaboration.md : problem with zoom meeting link

Seems like an old link that will not be used again. @despiegk @weynandkuijpers please confirm.

**Comment by hossnys** [comment]
all broken links fixed , except : info_grid/docs/online_meetings/agile_collaboration.md : problem with zoom meeting link , need to be confirmed by  @despiegk @weynandkuijpers
