### ISSUE TITLE
Converting capacity onto TF Grid

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_grid#46]
Digital Energy from Russia wants to convert some of their GIG capacity onto TF Grid. 
Like to start Zero-Os inside their G8 environment. Plan to setup ZOS as guest OS and connect to TF Grid

Contact: Dmitry Delyukin
dmitry.delyukin@digitalenergy.online

Contact at TF: @andhartl

**Comment by andhartl** [comment]
Hi Dmitry,
Please use this documentation to setup your farm by running zero OS in a vm: https://github.com/zero-os/home/tree/master/docs/farmers

**Comment by abdulgig** [comment]
Necessary documentation has been provided above, closing this ticket till any further response is received !
