### ISSUE TITLE
Farming node down after upgared to 1.5.0-rc1

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#49]
Hi, I upgraded my farm to 1.5.0-rc1 from development version. Now my node shows as down and still with the old os version. What should I do?
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/18591016/52962989-ed43be80-339e-11e9-8c1a-86add097d540.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/18591016/52963011-fa60ad80-339e-11e9-94ab-4bb15bd124de.png">

**Comment by Pishoy** [comment]
can connect the node to a monitor and tell me what is support IP that shown in physical node so i can access it remotely and check new image ?

**Comment by andhartl** [comment]
![unadjustednonraw_thumb_2b89](https://user-images.githubusercontent.com/18591016/53000970-d72f1000-3429-11e9-87dc-3f18c471493f.jpg)

**Comment by zaibon** [comment]
@andhartl we've identify a problem in the lastest build for the branch 1.5.0-rc1 which prevent the node robot to start. New build with fix is on the way. 
You will have to upgrade your kernel

**Comment by Pishoy** [comment]
the nodes does not has the support flag so it not easy to access it , at least i need a support flag to access it
please can you reinstall image by support flag ?

**Comment by Pishoy** [comment]
HI @andhartl  any update about above ?

**Comment by andhartl** [comment]
moved back to development branch. Will wait until I get the green light on 1.5.0-rc1
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/18591016/53300472-15706900-3848-11e9-895c-342dc23e2dfe.png">

**Comment by andhartl** [comment]
note: thought we need to shut down all backdoors for going live with the grid. so why are we still working with the support flag?

**Comment by Pishoy** [comment]
it just a flag, as i know you can remove it in any time but i have asked to you so we can access and check node ..

**Comment by Pishoy** [comment]
i think the issue may not regarding to image type ` 1.5.0-rc1` , it is may regarding to expired token or something else
if you need to run on ` 1.5.0-rc1` version, please reinstall node with this this image and enable support flag to check the problem cause
if not please close ticket

**Comment by andhartl** [comment]
solved by going back to dev version of zero os
