### ISSUE TITLE
Server booted with new image, doesnt show up in capacity

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_grid#51]
Customer: HPE
Contact: miroslaw.polski@hpe.com
Message: I have booted my server in Warsaw with a new image based on the latest master version (org hpe-cec, farm HPE-PL) and it didn’t make his way to the capacity.
ZeroTier network sees it as connected.

**Comment by zaibon** [comment]
We need more information. What is the zerotier ip it ? support ip ? 
Screenshot ? error message ? anything that would allow us to investigate our self or to have a clue what is happening.

**Comment by andhartl** [comment]
![image](https://user-images.githubusercontent.com/18591016/53323555-c6c1de00-38de-11e9-97ed-c522820ada1c.png)

**Comment by zaibon** [comment]
Seems the farmer id is expired, you need to generate a new one on the directory and reboot the node with it.

**Comment by mpolski** [comment]
I used an old image, by using the right image it shows up on on the list. So everything works as expected.
However, it would be nice to know when the FarmerID has expired and what the expiration actually means?
Since the FarmerID consists of a few things, is there a time limit if no nodes are seen using a given FarmerID for a period of time or something?

**Comment by abdulgig** [comment]
The farmerID is a token for security to prevent any unauthorized access to the nodes. 

@zaibon , please brief on the expiration time and renewal ?

**Comment by delandtj** [comment]
```python
oldjwt =".....youroldjwt"
newjwt =j.clients.itsyouonline.refresh_jwt_token(oldjwt)
```

**Comment by zaibon** [comment]
Documentation is on the way I'll add the link to it once it's updated in our wiki

**Comment by abdulgig** [comment]
Some documentation on JWT is under this link also,

[https://github.com/itsyouonline/identityserver/blob/master/docs/oauth2/jwt.md](url)

**Comment by zaibon** [comment]
https://github.com/threefoldfoundation/info_foundation/blob/development/docs/definitions/farmer_id.md
