### ISSUE TITLE
Protocols and Port numbers required for a node to connect to the grid

### ISSUE THREAD

**Issue by mpolski** [threefoldfoundation/info_grid#52]
Hello,
I work from behind a firewall, can you please advise on what port numbers/protocols should I allow outbound/inbound required to attach to the grid?

**Comment by mpolski** [comment]
![untitled](https://user-images.githubusercontent.com/20927637/53324815-03db9f80-38e2-11e9-96f1-a0c5dd49494b.png)

**Comment by mpolski** [comment]
to rephrase - I need port numbers/protocols for the node to appear on the grid (that's excluding all customer/user services that would be running on top of ZeroOS) that is ZeroTIer, revine? or other neccessary communiction

**Comment by Pishoy** [comment]
@mpolski seems node can not reach internet as it does not take any IP on any interface 
you don't need to any open port to start ZeroOS, if it is connected to internet properly will start normally

**Comment by mpolski** [comment]
![booting](https://user-images.githubusercontent.com/20927637/53553600-53b6a280-3b3e-11e9-9c1b-5a405ec5db12.png)

**Comment by mpolski** [comment]
So there are two stages. Stage one - PXE triggers ZeroOS download. Stage two - ZeroOS boots up.
Stage one works fine (as per the picture I am adding now), that is, I'm getting IP address from a local DHCP server, NTP fails as it's not allowed through the firewall. I downloads ZeroOS from bootstrap.gig.tech after exchaniging keys with letsencrypt.org and moves on to stage two. So to pass stage one - you need to have Internet connectivity working - which I have as you can see.

The previous picutre was taken after ZeroOS had been downloaded from the bootstrap.gig.tech, at that stage, ZeroOS needs an IP address from a local DHCP server. Why is it not getting it?
Looking at TCP dump, all other communication goes via HTTPs which is allowed.
So the question is, why ZeroOS once booted is not getting IP address from a local DHCP server? 
![booting_](https://user-images.githubusercontent.com/20927637/53558824-1c012800-3b49-11e9-9a0a-8ee91e550bfa.png)

**Comment by maxux** [comment]
Hello, please do Alt+Left or Right arrow on boot screen to get more logs.
I don't ser any reason why DHCP won't work.

About ports, you need to allows outgoing port: 80, 443 and 9900.
Mostly everything is done over https and 9900 is to reach zdb backend.

**Comment by Pishoy** [comment]
Hi @mpolski, close this case as no update
