### ISSUE TITLE
Farmers node does not show up on capacity but is online

### ISSUE THREAD

**Issue by siddiquagig** [threefoldfoundation/info_grid#53]
The farmer ( petersfarm ) booted his TF node with rc1.5.0 but his node does not appear on capacity.
![peter node](https://user-images.githubusercontent.com/25789724/53403001-36fa5d80-39cc-11e9-98f0-53a66aa48453.jpg)

Checking zrobot logs

**Comment by zaibon** [comment]
does TF node means this is a node used to run the TFchain ?
Cause if so, 1.5.0-rc1 is not what it should be running. There is a special 0-OS release for these blockchain nodes: https://bootstrap.grid.tf/generate/release-threefold-edge.nodes-0001

**Comment by siddiquagig** [comment]
Using the above image , farmer  has a kernel panic error,  have  asked him to  enable secure boot in BIOS as Maxime recommended for such nodes

**Comment by siddiquagig** [comment]
The farmer enabled secure boot (after disabling quiet Boot) in Bios but he still has a kernel panic error:

![kerenel panic](https://user-images.githubusercontent.com/25789724/53715267-b2e02400-3e6a-11e9-8244-98200cc199f5.jpg)

**Comment by maxux** [comment]
Well, from what I see, it's not enabled. This can be BIOS issue.

**Comment by pvanlier** [comment]
![photo_2019-03-05_06-57-41](https://user-images.githubusercontent.com/10684535/53784004-170af280-3f14-11e9-9c6c-4ddaa8f7d634.jpg)
When I enable secure boot in the bios, this is the message I get.

**Comment by maxux** [comment]
The USB key doesn't contains a signed bootloader.

**Comment by siddiquagig** [comment]
Used the image which Maxime sent for blockchain nodes:
 https://bootstrap.grid.tf/kernel/zero-os-release-threefold-edge.nodes-0001-signed.efi

Node is up now.

Farmer ( telegram: @pvanlier ) has yet to be explained the difference between capacity nodes and blockchain nodes.
