### ISSUE TITLE
new simulator for small node / rack node as done in bettertoken

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_grid#6]
do as gdoc (readonly) and excelsheet which can be downloaded

belongs in https://github.com/threefoldfoundation/info_grid/tree/master/docs/calculators

**Comment by despiegk** [comment]
source info has been updated, need some content which explains how it all works.

**Comment by weynandkuijpers** [comment]
Simulator done.  It is stored here: https://drive.google.com/open?id=1vE5A-l5jODhjVog1JkTE4mxZ3EqjiEJOBEC_ayhp-hY
