### ISSUE TITLE
wiki.grid.tf does not auto update from the master branch of the github-repo

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_grid#64]
I have made some updates in the master branch of Github - but updates are not reflected in the wiki bot wiki.grid.tf

**Comment by weynandkuijpers** [comment]
Page is: https://wiki.grid.tf/wiki/grid#/tf_farming/farming_setup

**Comment by weynandkuijpers** [comment]
Same issue is back - wiki content does not update from the master branch in github.  Can you please reset the updater?

**Comment by andhartl** [comment]
fixed
