### ISSUE TITLE
Why VMs?

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#66]
Why are we talking here vms. this should be containers, right?

<img width="979" alt="grafik" src="https://user-images.githubusercontent.com/18591016/54371213-4ee30a00-4679-11e9-9d56-fa5299000ae7.png">

**Comment by zaibon** [comment]
no this is VM. We provide virtual 0-OS. So it is a VM that is running 0-OS.

**Comment by zaibon** [comment]
Btw, this should have probably be a comment on the PR instead of merging it, then directly open an issue about what is now already merged ;-)
