### ISSUE TITLE
Create example/documentation on how to use the reserved capacity

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/info_grid#67]
Now that we reach the point where users will be able to reserve virtual 0-OS, we need to also provide some documentation and example on how to interact with it.

Ideas of examples:
- convert a docker image into flist and deploy the virtual 0-OS
- 0-OS API exploration
- ...

**Comment by zaibon** [comment]
@rkhamis @GlenDC 
can you advice what is available and ready in JSX to do this ?

**Comment by andrewayoub** [comment]
Here are a list of ideas that can be done, new ideas are most welcomed:
- [ ] instructions to create an flist from an existing docker file (using builders)
- [ ] a walk-through for zero-os client in JSX
- [ ] a detailed instructions of how to deal with a container ( networking, port forwarding, env variables, etc ...)

**Comment by rkhamis** [comment]
@andrewayoub isn't it that when we use builders we don't have a docker file? I think what @zaibon meant is dockerfile ---> flist.

But indeed, having a tutorial about builder ---> flist ---> starting a client with that flist would be good

**Comment by andrewayoub** [comment]
@rkhamis in 0-hub currently you can convert a docker image into flist but this image needs to be published first but not directly from a dockerfile, I opened a new issue here https://github.com/zero-os/0-hub/issues/36 to have this feature in the hub and then we can write an example for it.

**Comment by zaibon** [comment]
@andrewayoub you created the issue on the wrong repo, proper one is https://github.com/threefoldtech/0-hub/

**Comment by andrewayoub** [comment]
moved the issue to https://github.com/threefoldtech/0-hub/issues/12

**Comment by zaibon** [comment]
>  instructions to create an flist from an existing docker file (using builders)

Why not, although this seems like a power user feature already since you need to be able to write code for that. So I would say yes, but less prio

> a walk-through for zero-os client in JSX

This is really what I was referring too. What is the status of 0-os client in jsx. I though kosmos was going to be the tool normal user will have to use to talk to 0-os. But I didn't see any design/spec/code about that yet. Is there any ?

> a detailed instructions of how to deal with a container ( networking, port forwarding, env variables, etc)

Sure, but isn't kosmos supposed to be user friendly enough that people just "discover" feature through it ? But yeah general documentation about what 0-os can do should be improved.

**Comment by rkhamis** [comment]
0-OS client works perfectly well in kosmos.
We can always help people find what they need, there's a lot of features and you don't want people to drown in them

**Comment by zaibon** [comment]
> 0-OS client works perfectly well in kosmos.

Where is it located ? Cause I just tried `j.clients.zos` and it just return the low level protocol client.
How do I get a node object from the sal like we used to have in js9 ?

**Comment by rkhamis** [comment]
Try `j.sal_zos`.... Perhaps we should actually move that to the clients, it would make more sense there.

**Comment by zaibon** [comment]
Well, how it is now is different from what we used to have in js9. So yeah I think would be best to advertise the sal as the only client to use. the low level one is really just networking detail and should not be used directly.

**Comment by zaibon** [comment]
But still I though kosmos will brought a new vision on how to interact with 0-OS. Now it feel it's just another shell but with no real added value...

**Comment by zaibon** [comment]
closed in favor of https://github.com/threefoldtech/home/issues/168
