### ISSUE TITLE
US Farmer Bruce Needs Help with Upgrade to Zero OS master

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#68]
Can we help Bruce with upgrading his US nodes remotely to Zero OS master?

The names of those farms are: boulder1, prairiedog, todolossantos

Not sure if Ramez and team already helped with those farms/nodes before.

Can you please investigate and get back to Bruce? Thank you

**Comment by andhartl** [comment]
Bruce can best be reached via Telegram under @spectropol

**Comment by Pishoy** [comment]
Hi Bruce,

can you add itsyouonline organizations  of above farmers, so i can update them remotely ?
my iyo account is abdelmab@codescalers.com

**Comment by Pishoy** [comment]
prairiedog farm has been updated successfully
```
In [34]: ncl
Out[34]: Node <10.102.66.131:6379>

In [35]: ncl.ping()
Out[35]: 'PONG Version: master @Revision: 584ba6fe3b2891eb62c233f0c606315c97595ff9'

```
other farms, waiting Bruce to prepare and give me new farm_id of others

**Comment by Pishoy** [comment]
also boulder1 and todolossantos farm has been updated successfully 
- boulder1
```
In [46]: ncl
Out[46]: Node <10.102.242.21:6379>

In [47]: ncl.ping()
Out[47]: 'PONG Version: master @Revision: 584ba6fe3b2891eb62c233f0c606315c97595ff9'
```
- todolossantos
```
In [55]: ncl
Out[55]: Node <172.29.175.180:6379>

In [56]: ncl.ping()
Out[56]: 'PONG Version: master @Revision: 584ba6fe3b2891eb62c233f0c606315c97595ff9'

```
