### ISSUE TITLE
HPE DL 385 - Server booted ZeroOS / ILO reports Server still in POST

### ISSUE THREAD

**Issue by gneumann333** [threefoldfoundation/info_grid#73]
The Server bootet (like the 12 other Server of the same type at that location) 
ILO states that the Server is still Posting

Actions Taken:
Reset - no change
Cold Start - no change

Due to the Server still posting im unable to register the Server to HPE Support.

ZeroOS Details
MAC: 5480284e30d6 
OS Version: development   84862b5f8648743cd3cfbe11f7e8ccfd46e1d0b0
Flags support 
IP http://10.102.176.166:6600

ZeroOS Screen
![image](https://user-images.githubusercontent.com/39131062/54877633-8b54f980-4e21-11e9-871b-e8693257a6e7.png)

ILO:
![image](https://user-images.githubusercontent.com/39131062/54877707-2221b600-4e22-11e9-8b5e-bf427d1caff7.png)

Server logs show no errors

Guido

**Comment by Pishoy** [comment]
no error from node side, please check ILO version vs other nodes

**Comment by gneumann333** [comment]
ok, thank you for checking.
the node needs to be updated to the Master version of ZeroOs, hopefully this will resolve the issue.
