### ISSUE TITLE
Both nodes of farmer andybsa are down after upgrade

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#74]
Please reach out to @Andy_Brauer (Telegram user name) and help him to get his two nodes online again. Thanks
<img width="1147" alt="grafik" src="https://user-images.githubusercontent.com/18591016/54880726-658f1b00-4e48-11e9-935a-05f0006dcb31.png">

**Comment by Pishoy** [comment]
Hi can u tell me how you upgrade nodes ?

For node `3ca82aa04e3c` , node jwt is expired, Can you renew the jwt = ( farmer_id) 
then upgrade your node
```

In [31]: ncl.ping()
Out[31]: 'PONG Version: master @Revision: 584ba6fe3b2891eb62c233f0c606315c97595ff9'

In [32]: job = zrobot.client.subscribe('zrobot')

In [33]: job.stream()
Traceback (most recent call last):
  File "/.startup.py", line 45, in get_admin_organization
    claims = jwt.decode(token, iyo_pub_key)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 153, in decode
    options=defaults)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 461, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "/usr/local/lib/python3.5/dist-packages/jose/jwt.py", line 302, in _validate_exp
    raise ExpiredSignatureError('Signature has expired.')
jose.exceptions.ExpiredSignatureError: Signature has expired.

In [35]: ncl
Out[35]: Node <10.102.213.227:6379>

```

node `ac162d565330` is unreachable , can you verify that is properly connected to internet ? or send to me a screenshot to node

**Comment by andromedia** [comment]
Thank you Andreas and Michael
Strange as to why it expired but i have renewed the JVT and all is fine call can be closed.
