### ISSUE TITLE
Green Edge Cloud needs support to upgrade to Zero OS Masster

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#77]
Can you please help green edge cloud with upgrading their farms in the US, Canada and Austria? will ask Guido from green edge cloud to provide more info like router logins and zero os images.

**Comment by andhartl** [comment]
forwarded info from guido to bishoy via telegram
guido can be reached best via telegram: @guido_neumann

**Comment by Pishoy** [comment]
i have updated 4 sites ( Rochester, Toronto, Vienna 1, Vienna 2) successfully but there is some nodes have issues 

- about nodes that have not updated successfully this is [issue](https://github.com/threefoldtech/jumpscale_lib/issues/72) tracking

**Comment by Pishoy** [comment]
4 farmers should be okay now, only Tornto missing one node, will check it..

**Comment by Pishoy** [comment]
all 4 farmers are now up and running in master version
