### ISSUE TITLE
Valentyn's node is not showing after upgrade to amster

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#78]
this farmer 
<img width="520" alt="grafik" src="https://user-images.githubusercontent.com/18591016/55067127-72498400-507f-11e9-8657-c3f4672f051b.png">
upgraded to
<img width="402" alt="grafik" src="https://user-images.githubusercontent.com/18591016/55067246-aa50c700-507f-11e9-956e-559441f2b185.png">
but this does not show in capacity.threefoldtoken.com
<img width="875" alt="grafik" src="https://user-images.githubusercontent.com/18591016/55067302-c3f20e80-507f-11e9-9a95-a0a5ca679a1e.png">
please support him. best is to communicate through @nbabenko (telegram). thanks

**Comment by Pishoy** [comment]
issue with capacity registration method, @maxux will check it later

![image](https://user-images.githubusercontent.com/21987477/55483199-67b26000-5626-11e9-9a75-9a72f174f692.png)

**Comment by Pishoy** [comment]
@maxux  still the same issue after update to your last push in master 

```
In [5]: ncl = j.clients.zos.get('node', data = { 'host':'10.102.142.4', 'password_':jwt},)

In [6]: ncl.ping()
Out[6]: 'PONG Version: master @Revision: e95429abaf2d8a3e4d5fcf7bfd2d64b940a6a733'

In [7]: ncl.capacity.register()
[Thu04 08:52] - Capacity.py       :95  :_zos.capacity.capacity - ERROR    - error pusing total capacity to the directory: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n'
```

**Comment by Pishoy** [comment]
@andhartl 
The 500 error is just because the farmer id provided doesn't exists on the capacity website.
```

In [16]: ncl.kernel_args
Out[16]: 
{'intel_iommu': 'on',
 'kvm-intel.nested': '1',
 'console': 'tty1',
 'consoleblank': '0',
 'earlyprintk': 'serial,ttyS1,115200n8',
 'loglevel': '7',
 'zero-os-master.efi': '',
 'zerotier': 'c7c8172af1f387a6',
 'organization': '"valentinkorobko"',
 'support': '',
 'farmer_id': 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJTRDJaZlBjLWlyR3JKVHR5TGlKcmkwZFpxaGpWIiwiZXhwIjoxNTUzMTYwOTc4LCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJyZWZyZXNoX3Rva2VuIjoieFR1NXpwTmpzTEJEZVY3cUY1Z0hhcHVfbzRzNSIsInNjb3BlIjpbInVzZXI6bWVtYmVyb2Y6dmFsZW50aW5rb3JvYmtvIl0sInVzZXJuYW1lIjoic2lkZGlxdWEifQ.6qa0IkUim20Gi0ulfJSF2xjLYEc13QktwC5FzSuK6Y261fKH2E13PLbnW0ZLbCJ-R7l-V5GLz56l4G9lTMwGtKH7HIczQQKkSRULpQjDwj2HqXFnI6vGooR1VT5J7QdO'}
```

Please create new farmer_id with proper iyo org name

**Comment by maxux** [comment]
Or create a farmerid with the memberof requested, but you should use the farmerid provided by the capacity website.

**Comment by siddiquagig** [comment]
Issue solved by making new IYO organization-ID
![korobko](https://user-images.githubusercontent.com/25789724/55711157-30b0c580-59fd-11e9-8e5a-253dfbf9010c.JPG)
