### ISSUE TITLE
parthgalen node not showing in capacity.threefoldtoken.com

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_grid#88]
Please check why the node from parthgalen is not shown in the capacity.threefoldtoken.com website:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/18591016/56078386-ba8ad500-5de7-11e9-8d5e-b07765ebfb95.png">

**Comment by andhartl** [comment]
please communicate with Koen via Telegram. his username is @koenvictor

**Comment by andhartl** [comment]
Jan is on the issue already. pls check with him on status. 

above koen is the wrong one. please do not communicate with him

**Comment by PeterNashaat** [comment]
Tried to register the node manually 
got this error  :- 

```
In [8]: cc_node.capacity.register()
[Mon15 13:49] - Capacity.py       :95  :_zos.capacity.capacity - ERROR    - error pusing total capacity to the directory: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n'

```

**Comment by PeterNashaat** [comment]
checking why we have this issue

**Comment by PeterNashaat** [comment]
- Issue is fixed 
- it was old farmer_id , needed a new farmer_id and generated a new efi image and re-installed the node
 
![image](https://user-images.githubusercontent.com/13523434/56142138-6d049880-5f9e-11e9-8cc3-c06646a3884c.png)

- Node is up and running 

![image](https://user-images.githubusercontent.com/13523434/56142160-7988f100-5f9e-11e9-9eed-b2c2a47997a5.png)
