### ISSUE TITLE
make sure no duplication in definitions

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_grid#9]
e.g. https://threefoldfoundation.github.io/info_grid/#/legal/definitions

should use definitions as used on foundation wiki, can include raw .md from github

**Comment by weynandkuijpers** [comment]
let's agree to have all the generic / major defintions listed in the foundation wiki - augmented by specific definitions in the grid and other wiki's.

**Comment by andhartl** [comment]
done on info_foundation
