### ISSUE TITLE
WIKI: Correct '/docs/faq/"

### ISSUE THREAD

**Issue by DeKyper** [threefoldfoundation/info_grid#98]
Issue: some of answers are not full:

performance.md
promote_appdev.md
proof_of_stake.md
capacity_rules.md
emerging_markets.md
minio.md - empty
storage_principles.md

Link: https://github.com/threefoldfoundation/info_grid/tree/development/docs/faq

**Comment by andhartl** [comment]
closed for now. will reopen in more detail
